### ISSUE TITLE
improve handling of forge bindings

### ISSUE THREAD

**Issue by alysiahuggins** [EspressoSystems/espresso-sequencer#1068]
**Goal**:  decide if bindings should be committed and if so, decide which folders it should be created for and write a `forge bind` command which handles it appropriately. 

**Issue**: Using this command `forge bind --contracts ./contracts/src --crate-name contract-bindings --bindings-path contract-bindings --overwrite --force`, I still get bindings generated for other folders within the `./contracts` folder. e.g. the `./contracts/demo` folder

**Context**:
what we definitely don't want:

test/ (esp test/mocks/ which look like normal contract)
scripts/
lib/ (esp forge's std library)

what we strongly prefer NOT to have:

demo code

**Comment by sveitser** [comment]
Are there still issues with the bindings? If yes, what exactly are they?

My 2c:

It's very useful to have the bindings somewhere such that they can easily be used by other crates without having to bring in a foundry etc. currently we have them committed in the repo where the contracts live because it makes it easy to include them in rust crates (via a git dependency). It also allows us to make sure the bindings are in sync with pre-commit hooks that we can run locally and on the CI.

I agree that we shouldn't generate useless bindings so if we can exclude bindings for tests etc. that's a great improvement.

Maybe at some point we move the contract and the bindings to a separate repo but as long as they are under heavy development I think it's more ergonomic for us to keep them in this repo.

We could also exclude the bindings from being expanded in github diffs: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

cc @alysiahuggins @alxiong @philippecamacho

**Comment by philippecamacho** [comment]
Potentially useful: https://github.com/foundry-rs/foundry/issues/4375 and corresponding PR https://github.com/foundry-rs/foundry/pull/7266
