### ISSUE TITLE
escape hatch : purge elements from stateUpdates and hotShotCommitments arrays once it has over 10 days of worth of data

### ISSUE THREAD

**Issue by alysiahuggins** [EspressoSystems/espresso-sequencer#1541]
Arising out of this PR https://github.com/EspressoSystems/espresso-sequencer/pull/1493

**Comment by alysiahuggins** [comment]
With the current implementation, both the `lagOverThreshold` and `getHotShotCommitment` functions depend on arrays being sorted in ascending order. To maintain only 10 days worth of sorted data at a time, one option is to remove elements from the array in a FIFO basis which requires iterating through the entire array to shift each element down. 

Instead, I think the data should be added to the array in a wrap around method and then have the array sorted when either `lagOverThreshold` or `getHotShotCommitment` is called. The wrap around method works such that when there's 10 days worth of data, the first element in the array 

Reasons for the latter approach instead of the former: 
(i) the arrays are updated each time the light client contract receives an update and thus will increase gas requirements to remove an element by shifting, 
(ii) the functions that depend on these arrays are called very infrequently and thus sorting only on those instances would be more efficient

@sveitser

**Comment by sveitser** [comment]
@alysiahuggins I think it's a good idea to do the purging when sending the update so that we don't need to call another public method.

How about we add a state variable with the index of the earliest populated entry of the array. This could then be used when sending state updates to check if any entries in the array need to be removed and remove them. AFAIK the length of the array will remain unchanged and the removal effectively zeroes the entries, incurring a gas refund. 

This way the data always stays sorted by L1 block number and we have an easy way to access the beginning for purging and the end for the escape hatch.

One potential problem with this approach is however that if there was no update for a long time, many items may need to be purged which could cost a lot of gas. However, due to incurring a gas refund on removing entries from the map it may not be a problem. This needs to be tested though because we previously ran into some issues with gas estimation when gas refunds were involved.

**Comment by alysiahuggins** [comment]
Thanks for the response @sveitser and alternative approach. 

> How about we add a state variable with the index of the earliest populated entry of the array. This could then be used when sending state updates to check if any entries in the array need to be removed and remove them. AFAIK the length of the array will remain unchanged and the removal effectively zeroes the entries, incurring a gas refund.

This can work but I believe the length of the array would continue to grow even if you do delete arr[index] or arr[index] = 0. Whereas arr.pop() would reduce the length of the array but from the end first (LIFO).  So the storage required to maintain that array grows over time. Though computationally, we would only ever iterate over a fixed number array elements (10 days of blocks) so the gas required for that should be constant too?

> One potential problem with this approach is however that if there was no update for a long time, many items may need to be purged which could cost a lot of gas. However, due to incurring a gas refund on removing entries from the map it may not be a problem. This needs to be tested though because we previously ran into some issues with gas estimation when gas refunds were involved.

Since the is to store 10days worth of blocks, even if there's a gap, as long as we have been purging each time we update state, I think it should be fine.

**Comment by sveitser** [comment]
Yes the "array length" would grow indefinitely. However I don't see a problem with that. We can also use a map but then we need to keep track of the latest index (as substitute for array length) as well. I believe under the hood arrays are very similar to maps. I think both of these approaches are fine.

> So the storage required to maintain that array grows over time. 

I'm not sure I follow. AFAIK when we set an array element to zero it no longer needs to be stored.
