### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1715]
When running tests locally with `just test` it's currently rather rare that it all passes. We should fix this.

Tests that sometimes fail:

- [ ] `non_permissioned::test::test_non_permissioned_builder` (fails often)
- [ ] `api::fs::generic_tests::catchup_test_with_query_module`
- [ ] `api::test::state_signature_test_without_query_module`
- [ ] `persistence::sql::generic_tests::test_voted_view`
- [ ] `hotshot_commitment::test::test_idempotency` 
- [ ] `api::test::test_merklized_state_api` (does not fail but runs seemingly forever)

There are some more flaky tests but I lost that console output. If you find more flaky tests please at them here.

Note that failures are sometimes be caused by other tests interfering with the failing test.

**Comment by sveitser** [comment]
@tbro @Ayiga you've probably run the tests many times in the last few days. Do we still have flaky tests, or should we close this?

**Comment by Ayiga** [comment]
I haven't really received many failures of the past couple of days, but I just re-ran the tests to be certain.

All of the tests seem to pass when run with 1 test thread, when run on the default nix environment (though the tests run faster when compiled with --release I believe):

```sh
cargo test --lib --all-features -- --test-threads 1
```

Though, sometimes the tests emit error messages like:
- `hotshot_commitment::test::test_idempotency`:
```
test hotshot_commitment::test::test_idempotency ... 2024-08-14T19:37:19.718031Z ERROR anvil::cmd: Failed to dump state err=CreateFile { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "/tmp/nix-shell.UwydHT/.tmpVuRdOs/state.json" }
ok
```

Which can look like an error / failure if you don't see the `ok` underneath it.  I was doing some testing yesterday with a larger number of test-threads.  I think I was able to get it to pass with 6 threads once, but then a second run it failed.  So the flaky tests may just be due to running the tests without limiting the number of tests threads being run.

**Comment by tbro** [comment]
> @tbro @Ayiga you've probably run the tests many times in the last few days. Do we still have flaky tests, or should we close this?

I haven't seen any. Only the one under metrics that @Ayiga was fixing (did fix?). Tests are running with `--retries` so we should be see them marked in CI if they do turn up. I guess we would have to check the CI output occasionally to see them though.

**Comment by Ayiga** [comment]
Closing as these test no longer seem to be flaky.
