### ISSUE TITLE
L03: Challenge generation logic deviates from the protocol specification

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1735]
**Affected Code:** Transcript.sol (line 45)

**Summary:** The transcript is a log of public inputs, verifying key, and all the messages exchanged between the prover and the verifier. According to the PLONK paper and the Fiat Shamir heuristic, challenges are generated by hashing the current state of the transcript. However, the current implementation prepends the hash of the current transcript to the transcript itself and then hashes that to generate the new challenge. This additional step deviates from the protocol specification. Additionally, the function `getAndAppendChallenge` copies both the hash and the transcript to a new memory location each time it is called. This practice is inefficient and unnecessary.

**Suggestion:** We suggest directly hashing the transcript to align with the standard protocol specifications. Additionally, when generating multiple challenges for the same round (such as $\beta$ and $\gamma$), concatenate an index to the transcript and hash the result. For example:
$\beta = H(transcript, 0)$
$\gamma = H(transcript, 1)$

**Comment by alxiong** [comment]
Agree, 

I have removed the `state` (previously `H(state | transcript)`, right now simply `H(transcript)`) in jellyfish: https://github.com/EspressoSystems/jellyfish/issues/618, and haven't worked on contract yet. 

> Additionally, when generating multiple challenges for the same round (such as and ), concatenate an index to the transcript and hash the result.

Even with the above change, when generating challenges for the same round, we simply would call `gen_and_append_challenge()` twice instead of using index,
if we want to adopt that, we need to modify our `trait Trascript` API a little bit to allow generation of multiple challenges per round, (current trait doesn't have this notion) 

I don't think our current approach is wrong or insecure. just slightly different from plonk paper. 
so what's your take? @chancharles92 @philippecamacho

**Comment by philippecamacho** [comment]
> I don't think our current approach is wrong or insecure. just slightly different from plonk paper.
so what's your take? @chancharles92 @philippecamacho

Yes, I agree the current contract code is not insecure, it just deviates from the Plonk paper and is inefficient.  I think it is inherited from an earlier version of the transcript that was even less efficient. See https://github.com/EspressoSystems/espresso-sequencer/pull/1337/files

**Comment by alxiong** [comment]
After reading other's transcript implementation, we realize that the most commonly adopted way to achieve domain separation (for "squeeze" or "challenge gen") so that continuous call of `get_challenge()` in the same round would give different challenges, is not via index like Plonk paper: `H(transcript | 0)`, but rather via `state = H(transcript so far)` and each squeeze would clear out the entire `transcript`. 

this "using state in place of prior transcript bytes" approach is taken by [Axiom](https://github.com/axiom-crypto/snark-verifier/blob/main/snark-verifier/src/system/halo2/transcript/evm.rs#L77-L106), [Han](https://github.com/han0110/halo2-solidity-verifier/blob/main/src/transcript.rs#L71) from PSE, [ArgumentComputer ](https://github.com/han0110/halo2-solidity-verifier/blob/main/src/transcript.rs#L71)(prev. Lurks lab), and Succint's [SP1 contract](https://github.com/succinctlabs/sp1-contracts/blob/main/contracts/src/v1.1.0/PlonkVerifier.sol#L485-L518) (Succint uses both `state`, although not explicitly call it in their contract, and also "labelled challenge" to domain separate).

A slight advtange of this over "plonk paper" approach is: this only requires copying of a single word (32 byte) to make all preimage fields continuous in memory (a prerequisite to apply hash on it); whereas to squeeze multiple challenges with index appended, would require copying the entire transcript to free memory sratch pad at least once. 

I think it's reasonable to follow this instead of strictly following Plonk paper?

cc @chancharles92 @philippecamacho @shresthagrawal
