### ISSUE TITLE
I02: Redundant endianness reversal in transcript generation and serialization logic

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1739]
**Affected Code:**
• Transcript.sol (lines 45,81)
• PlonkVerifier.sol (line 173)
• BN254.sol (lines 313,331)

**Summary:** The current implementation reverses the endianness of all entries appended to the transcript. This is done to ensure compatibility with previous off-chain implementations. However, this step is redundant for the correct functioning of the Fiat-Shamir heuristic.

**Suggestion:** We suggest removing the endianness reversal step from the transcript generation and point serialization/deserialization to simplify the code and reduce the gas cost.

**Comment by alxiong** [comment]
Agree, 

I have adjust the endianness at jellyfish side in https://github.com/EspressoSystems/jellyfish/pull/619

Yet to update the contract and contract tests.

**Comment by alxiong** [comment]
In the old code, we used `to_bytes!()` macro from arkworks, which by default would call [`serialize_compress()`](https://docs.rs/ark-serialize/latest/ark_serialize/trait.CanonicalSerialize.html#method.serialize_compressed) in little endian: for G1 point, it will only takes compress 2 254-bit fields into a single u256 value, encoding the sign of y coordinate using a single bit. 

in https://github.com/EspressoSystems/jellyfish/pull/619, I only switch to big endian and forgot to use the compressed form. So G1 point would serialize into 2 bytes32 value. 

Now I wonder maybe it's better to just use the uncompressed form in contract altogether and completely remove the `g1Serialize()` and `g1Deserialize()`
The only added cost is that for hashing a G1 point to transcript, we will append 2 bytes32 instead of 1; but we are saving the serializing logic and having less code.

cc @shresthagrawal @philippecamacho
