### ISSUE TITLE
I07: Inconsistent definition and usage of COSET_Ki constants

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1743]
**Affected Code:**
• Transcript.sol (line 104-L119)
• PlonkVerifier.sol (line 28-L35)

**Summary:** The `COSET_Ki` constants are used across multiple contracts. In the PlonkVerifier contract, these are defined as constants, whereas in the Transcript contract, they appear as magic numbers. This can lead to difficulties in maintaining the codebase.

**Suggestion:** We recommend refactoring the code to reference a single source of truth for the `COSET_Ki` constants. This can be achieved by defining these constants in a common library or a shared contract.

**Comment by alxiong** [comment]
While I definitely agree with this in principle, I think the challenge comes from the limitation of Library: library can't store global variables iirc. 

Does CommonPrefix recommend turning them all to contracts? (I don't see much downside since we hardly would reuse the library, and don't mind too much on one-time deployment cost)

**Comment by shresthagrawal** [comment]
`COSET_Ki` are constants in the codebase. One can have constants in the solidity library (eg. [FixedPoint.sol](https://github.com/Uniswap/solidity-lib/blob/c01640b0f0f1d8a85cba8de378cc48469fcfd9a6/contracts/libraries/FixedPoint.sol#L23)). Thought it is also fine to have them in a shared contract and set them as immutable constants within the constructor.

**Comment by philippecamacho** [comment]
Closed in #1836.
