### ISSUE TITLE
Move example-l2 into its own repo

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso-sequencer#622]
It is not required to build or run the sequencer, so this is good for modularity, and also allows us to license the example-l2 separately.

**Comment by ImJeremyHe** [comment]
I've created a new repo for the `example-l2` and make a [PR](https://github.com/EspressoSystems/sequencer-example-l2/pull/1) to let it work normally. Also a PR #655 to remove the directory.

You can see that I copied some files like `.env`, `flake.nix` from this repo, referenced crates from this repo by `git` and `tag`. I think it might not be a good way to separate them for now because we need to know that if any update will cause errors in the `example` and we should keep them in one CI system.
