### ISSUE TITLE
Fee token L1 contract

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#935]
Allow “builders” to deposit ETH onto the Upgradable L1 Fee Token contract so that they can participate with the Hotshot sequencer.

## Functions

- Deposit
- Include deposit events
- add a cap to how much can be deposited to prevent fat finger errors
- ensure deposits are above some mimimum amount. See discussion [below](https://github.com/EspressoSystems/espresso-sequencer/issues/935#issuecomment-1889791196).

## Others

* Make the contract upgradable and add a test that the withdraw function can be added afterwards along the lines of https://github.com/EspressoSystems/espresso-sequencer/blob/0621b140637318aae2c55af34e37db51a6707649/contracts/test/BoxUpgrade.t.sol#L73

**Comment by alysiahuggins** [comment]
Allow “builders” to deposit ETH onto the _Upgradable_ L1 Fee Token contract so that they can participate with the Hotshot sequencer. 

**Functions**
1. Deposit
- Include deposit events
- add a cap to how much can be deposited to prevent fat finger errors

**Tests**
- Upgrades: Verify via tests that withdrawal works when the smart contract is upgraded

**Comment by philippecamacho** [comment]
Note do we need to ensure a minimum deposit amount? cc @jbearer @nomaxg  I remember we discussed this at some point but not sure this is really needed.

**Comment by philippecamacho** [comment]
We should also update the deployment script and document how to use it.
