### ISSUE TITLE
Contracts upgrade deployment script

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#999]
Specify and implement the scripts to upgrade the contracts, including tests to ensure the deployment is successful.
Take into account considerations introduced in #975 and other constraints such as the need for an atomic upgrade across all the contracts.

- Automatically Rollback if post-deployment tests fail

Potential steps
- create deployment script that allows for deployments with a multisig wallet
- add tests that must be satisfied in order for the deployment to be successful
- perform upgrade deployment with forked version of mainnet
- consider a deployment that executes in one transaction and fails if the test cases aren't satisfied

**Comment by alysiahuggins** [comment]
I was stuck on deploying & upgrading the light client contract for a bit - I contacted openzeppelin defender support and this issue (https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/26) created by the team. In the end using the `internal` visibility for library functions worked - adding this info here for documentation purposes.

**Comment by alysiahuggins** [comment]
I'm reducing the scope until we get more support from OpenZeppelin.

I had written these potential steps on the ticket:
```
1. create deployment script that allows for deployments with a multisig wallet
2. add tests that must be satisfied in order for the deployment to be successful
3. perform upgrade deployment with forked version of mainnet
4. consider a deployment that executes in one transaction and fails if the test cases aren't satisfied
```

Step 1 is done 
- by using openzeppelin defender, we get some upgradable validation checks e.g.
- `upgrade safety`(e.g. the contract does not have a constructor, an initialize function exists etc https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-does-it-mean-for-a-contract-to-be-upgrade-safe)
- `upgrade compatibility` (e.g. compatible storage layout https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-does-it-mean-for-an-implementation-to-be-compatible)

Steps 2 & 3 
- have not been implemented because I'm not clear on how to test with a forked version of mainnet whilst using openzeppelin defender. This talks about using forked networks https://docs.openzeppelin.com/defender/v2/guide/forked-network but it does not support upgrades. which is when the tests are mostly needed.


Step 4 relies on step 2/3 working

[image.png](https://espresso.zulipchat.com/user_uploads/40450/qnt0PYntrYCSoK9ObbXFAPpn/image.png)
I asked OpenZeppelin support about the best way to test locally with Defender and his response was to ask in a forum.


So to conclude, I think it would be best to reduce the scope of this ticket to just getting the multisig deployment and upgrade working (since we have tests that test that the upgraded contract does indeed implement with the correct business logic). And then create another ticket that focus on testing with OPZ Defender locally.

Another thought is that I can create tests with a forked version of mainnet but without OPZ defender (but I still think that can be another ticket)

**Comment by alysiahuggins** [comment]
I can also confirm that you can use a hardware wallet as a signer in the multisig wallet.

**Comment by alysiahuggins** [comment]
Issue created for local testing environment https://github.com/EspressoSystems/espresso-sequencer/issues/1251

**Comment by philippecamacho** [comment]
See https://github.com/EspressoSystems/espresso-sequencer/pull/1248

**Comment by philippecamacho** [comment]
> I asked OpenZeppelin support about the best way to test locally with Defender and his response was to ask in a forum.

> So to conclude, I think it would be best to reduce the scope of this ticket to just getting the multisig deployment and upgrade working (since we have tests that test that the upgraded contract does indeed implement with the correct business logic). And then create another ticket that focus on testing with OPZ Defender locally.

> Another thought is that I can create tests with a forked version of mainnet but without OPZ defender (but I still think that can be another ticket)

Yes, sure.
